INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Hey", "Music", 1000, NULL, NULL);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Been", "Music", 800, NULL, NULL);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Trying", "Music", 900, NULL, NULL);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("To", "Music", 700, NULL, NULL);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Meet", "Music", 950, NULL, NULL);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("You", "Book", 1100, NULL, NULL);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Pixies", "Book", 1050, NULL, NULL);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Yes", "Book", 950, NULL, NULL);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("No", "Book", 1300, NULL, NULL);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Maybe", "Book", 1250, NULL, NULL);

INSERT INTO users (name, age) VALUES ("Joe", 25);
INSERT INTO users (name, age) VALUES ("James", 27);
INSERT INTO users (name, age) VALUES ("Joan", 26);
INSERT INTO users (name, age) VALUES ("Jack", 28);
INSERT INTO users (name, age) VALUES ("Jerry", 28);
INSERT INTO users (name, age) VALUES ("Jeremiah", 30);
INSERT INTO users (name, age) VALUES ("John", 26);
INSERT INTO users (name, age) VALUES ("Josephine", 30);
INSERT INTO users (name, age) VALUES ("Jackie", 28);
INSERT INTO users (name, age) VALUES ("Jones", 24);
INSERT INTO users (name, age) VALUES ("Jared", 26);
INSERT INTO users (name, age) VALUES ("Jonah", 28);
INSERT INTO users (name, age) VALUES ("Jonas", 24);
INSERT INTO users (name, age) VALUES ("Jacques", 30);
INSERT INTO users (name, age) VALUES ("Juno", 26);
INSERT INTO users (name, age) VALUES ("Jah", 30);
INSERT INTO users (name, age) VALUES ("Jane", 24);
INSERT INTO users (name, age) VALUES ("Joseph", 28);
INSERT INTO users (name, age) VALUES ("Jonathan", 26);
INSERT INTO users (name, age) VALUES ("Jark", 24);

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 7, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 9, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 10, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 11, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 12, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 13, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 14, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 15, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 16, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 17, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 18, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 19, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 2, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 7, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 8, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 9, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 10, 1);